name: Node.js CI and Codecov
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node: ["14", "16"]
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests using jest
        run: |
          npm ci
          npx nyc --reporter=lcov jest
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
      
